### ISSUE TITLE
Some suggestion of using nutsdb

### ISSUE THREAD

**Issue by bigboss2063** [yudhasubki/blockqueue#3]
Hi yudhasubki. I feel that in the usage scenario of using nutsdb as a queue, it is not necessary to enable the LRU cache of nutsdb. This will bring additional overhead. And the default write strategy is to call Sync every time, so maybe this could provide a user option to let them choose. 😁

BTW, I'm interesting of your projects. If there are something I can do, I'm glad to help (But for now I'm working on my schoolwork 😢).

**Comment by bigboss2063** [comment]
Just some little advises.

**Comment by yudhasubki** [comment]
Halo @bigboss2063 it's an honor to hear advice from the maintainer of NutsDB 😄 

Sounds good, I'll add some configurations to let users choose the sync method. Btw for the LRU Cache, how to disable it? I didn't find it in the NutsDB documentation, would you mind giving me some examples?

For the next plan, I want to make my network protocol instead of using HTTP, if you have free time just poke me, and feel free to discuss.

**Comment by bigboss2063** [comment]
I checked our code of LRU part. There is currently no way to completely turn off the LRU cache, but you can set the option `HintKeyAndRAMIdxCacheSize` to 0. 

In next version we will optimize it which you could control it with a switch 😁.

**Comment by yudhasubki** [comment]
Woh, thanks for the suggestion @bigboss2063, I already implement it first before release for the next version 🥂

**Comment by bigboss2063** [comment]
hhh. What a nice author! If you want to more API of nutsdb, just open an issue, or implement it directly 😁.
